import React, { useState, useEffect, useRef } from 'react';
import { Play, Pause, Loader2, Maximize, Share2, Download, X } from 'lucide-react';

export function ImageViewer({ src, alt }: { src: string; alt: string }) {
  const [isFullscreen, setIsFullscreen] = useState(false);

  const handleDownload = async (e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      const response = await fetch(src);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `nova-image-${Date.now()}.jpg`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      window.open(src, '_blank');
    }
  };

  const handleShare = async (e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      if (navigator.share) {
        await navigator.share({
          title: 'Generated by Nova',
          url: src
        });
      } else {
        await navigator.clipboard.writeText(src);
        alert('URL copied to clipboard!');
      }
    } catch (err) {
      console.log('Share failed', err);
    }
  };

  return (
    <>
      <div className="group relative mt-4 inline-block w-full max-w-2xl overflow-hidden rounded-xl bg-black ring-1 ring-white/10">
        <img src={src} alt={alt} className="w-full h-auto object-contain transition-transform duration-700 ease-out group-hover:scale-[1.02]" loading="lazy" />
        <div className="absolute top-4 right-4 flex gap-2 opacity-0 transition-opacity duration-200 group-hover:opacity-100">
          <button onClick={() => setIsFullscreen(true)} className="flex h-9 w-9 items-center justify-center rounded-lg bg-black/60 text-white backdrop-blur-md transition-colors hover:bg-black/80 hover:text-nova-accent" title="Fullscreen">
            <Maximize size={18} />
          </button>
          <button onClick={handleShare} className="flex h-9 w-9 items-center justify-center rounded-lg bg-black/60 text-white backdrop-blur-md transition-colors hover:bg-black/80 hover:text-nova-accent" title="Share">
            <Share2 size={18} />
          </button>
          <button onClick={handleDownload} className="flex h-9 w-9 items-center justify-center rounded-lg bg-black/60 text-white backdrop-blur-md transition-colors hover:bg-black/80 hover:text-nova-accent" title="Download">
            <Download size={18} />
          </button>
        </div>
      </div>

      {isFullscreen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/95 p-4 backdrop-blur-xl transition-all" onClick={() => setIsFullscreen(false)}>
          <button className="absolute top-6 right-6 rounded-full bg-white/10 p-2.5 text-white backdrop-blur-md transition-colors hover:bg-white/20 hover:text-nova-accent" onClick={() => setIsFullscreen(false)}>
            <X size={24} />
          </button>
          <img src={src} alt={alt} className="max-h-full max-w-full object-contain rounded-lg shadow-2xl" onClick={(e) => e.stopPropagation()} />
        </div>
      )}
    </>
  );
}

export function VideoViewer({ src, alt }: { src: string; alt: string }) {
  const [status, setStatus] = useState<'rendering' | 'ready' | 'playing' | 'paused'>('rendering');
  const [progress, setProgress] = useState(0);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const timerRef = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    // Simulate initial rendering time
    const renderTimer = setTimeout(() => {
      setStatus('ready');
    }, 4500); // 4.5s processing simulation
    return () => clearTimeout(renderTimer);
  }, []);

  useEffect(() => {
    if (status === 'playing') {
      timerRef.current = setInterval(() => {
        setProgress(p => {
          if (p >= 100) {
            setStatus('ready');
            clearInterval(timerRef.current!);
            return 0;
          }
          return p + (100 / 300); // 30 seconds = 300 ticks of 100ms
        });
      }, 100);
    } else if (timerRef.current) {
      clearInterval(timerRef.current);
    }
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [status]);

  const togglePlay = (e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    if (status === 'rendering') return;
    if (status === 'playing') setStatus('paused');
    else setStatus('playing');
  };

  const handleDownload = async (e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      const response = await fetch(src);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `nova-video-${Date.now()}.mp4`; // UX simulation
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
    } catch(err) { window.open(src, '_blank'); }
  };

  const handleShare = async (e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      if (navigator.share) {
        await navigator.share({
          title: 'Nova Generated Video',
          url: src
        });
      } else {
        await navigator.clipboard.writeText(src);
        alert('URL copied to clipboard!');
      }
    } catch (err) {
      console.log('Share failed', err);
    }
  };

  return (
    <>
      <div 
        className="group relative mt-4 w-full max-w-2xl overflow-hidden rounded-xl bg-black ring-1 ring-white/10 aspect-video cursor-pointer"
        onClick={() => togglePlay()}
      >
        <img 
          src={src} 
          className={`w-full h-full object-cover transition-transform ease-linear origin-center ${status === 'playing' ? 'scale-110 duration-[30000ms]' : status === 'rendering' ? 'scale-105 blur-sm opacity-50 duration-700' : 'scale-100 duration-500'}`}
          alt={alt} 
          loading="lazy" 
        />
        
        {/* Top-Right Actions */}
        {status !== 'rendering' && (
          <div className="absolute top-4 right-4 flex gap-2 opacity-0 transition-opacity duration-200 group-hover:opacity-100 z-10" onClick={e => e.stopPropagation()}>
            <button onClick={() => setIsFullscreen(true)} className="flex h-9 w-9 items-center justify-center rounded-lg bg-black/60 text-white backdrop-blur-md transition-colors hover:bg-black/80 hover:text-nova-accent" title="Fullscreen">
              <Maximize size={18} />
            </button>
            <button onClick={handleShare} className="flex h-9 w-9 items-center justify-center rounded-lg bg-black/60 text-white backdrop-blur-md transition-colors hover:bg-black/80 hover:text-nova-accent" title="Share">
              <Share2 size={18} />
            </button>
            <button onClick={handleDownload} className="flex h-9 w-9 items-center justify-center rounded-lg bg-black/60 text-white backdrop-blur-md transition-colors hover:bg-black/80 hover:text-nova-accent" title="Download (MP4)">
              <Download size={18} />
            </button>
          </div>
        )}

        {/* State Overlays */}
        <div className="absolute inset-0 flex flex-col items-center justify-center bg-black/10 transition-colors">
          {status === 'rendering' ? (
            <div className="flex flex-col items-center gap-4 backdrop-blur-md bg-black/60 px-6 py-5 rounded-2xl border border-white/10 shadow-2xl">
              <Loader2 size={40} className="animate-spin text-nova-accent" />
              <div className="flex flex-col items-center">
                 <span className="text-sm font-semibold text-white drop-shadow-md">Rendering 30s Video...</span>
                 <span className="text-xs text-gray-400 mt-1 font-mono">allocating GPU resources</span>
              </div>
            </div>
          ) : status !== 'playing' ? (
            <div className="flex h-20 w-20 items-center justify-center rounded-full bg-nova-accent/90 text-white shadow-xl backdrop-blur-md transition-transform hover:scale-110">
              <Play size={32} className="ml-[4px]" fill="currentColor" />
            </div>
          ) : (
            <div className="opacity-0 group-hover:opacity-100 flex h-20 w-20 items-center justify-center rounded-full bg-black/60 text-white shadow-xl backdrop-blur-md transition-all hover:scale-110 hover:bg-nova-accent/90">
              <Pause size={32} fill="currentColor" />
            </div>
          )}
        </div>

        {/* Status bar */}
        <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/90 via-black/40 to-transparent p-4 pl-5 pr-5 pt-16">
          {status === 'rendering' ? (
            <div className="flex items-center gap-4">
              <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-white/20">
                <div className="h-full w-full animate-pulse bg-nova-accent rounded-full origin-left shrink-0 scale-x-50"></div>
              </div>
              <div className="text-xs font-semibold text-nova-accent drop-shadow-md animate-pulse">Processing...</div>
            </div>
          ) : (
            <div className="flex items-center gap-4">
              <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-white/30 cursor-pointer hover:h-2 transition-all" onClick={(e) => {
                  e.stopPropagation();
                  const bounds = e.currentTarget.getBoundingClientRect();
                  const pct = (e.clientX - bounds.left) / bounds.width;
                  setProgress(pct * 100);
                }}>
                <div className="h-full bg-nova-accent shadow-[0_0_12px_rgba(99,102,241,1)] relative" style={{ width: `${progress}%`, transition: status === 'playing' ? 'width 0.1s linear' : 'none' }}>
                   <div className="absolute right-0 top-1/2 -translate-y-1/2 w-3 h-3 bg-white rounded-full shadow-md scale-0 group-hover:scale-100 transition-transform"></div>
                </div>
              </div>
              <div className="text-xs font-semibold text-white font-mono min-w-[36px] text-right drop-shadow-md">
                0:{Math.floor((progress / 100) * 30).toString().padStart(2, '0')}
              </div>
            </div>
          )}
        </div>
        
        <div className="absolute top-4 left-4 rounded bg-black/60 px-2.5 py-1 text-xs font-semibold tracking-wide text-white backdrop-blur-md flex items-center gap-1.5">
          {status === 'rendering' ? (
             <><div className="w-1.5 h-1.5 rounded-full bg-amber-400 animate-pulse"></div>Offline Render</>
          ) : (
             <><div className="w-1.5 h-1.5 rounded-full bg-emerald-400"></div>HQ • 30s</>
          )}
        </div>
      </div>

      {/* Fullscreen Viewer */}
      {isFullscreen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black backdrop-blur-xl" onClick={() => setIsFullscreen(false)}>
          <button className="absolute top-6 right-6 rounded-full bg-white/10 p-2.5 text-white hover:bg-white/20 hover:text-nova-accent transition-colors z-20" onClick={() => setIsFullscreen(false)}>
            <X size={24} />
          </button>
          <div className="relative w-full max-w-[90vw] max-h-[90vh] aspect-video group" onClick={e => e.stopPropagation()}>
            <img 
              src={src} 
              className={`w-full h-full object-contain transition-transform ease-linear origin-center ${status === 'playing' ? 'scale-105 duration-[30000ms]' : 'scale-100 duration-500'}`}
              alt={alt} 
            />
            <div className="absolute inset-0 flex flex-col items-center justify-center bg-black/10 transition-colors cursor-pointer" onClick={togglePlay}>
               {status === 'rendering' ? (
                <div className="flex flex-col items-center gap-4 backdrop-blur-md bg-black/60 px-8 py-6 rounded-2xl">
                  <Loader2 size={48} className="animate-spin text-nova-accent" />
                </div>
              ) : status !== 'playing' ? (
                <div className="flex h-24 w-24 items-center justify-center rounded-full bg-nova-accent/90 text-white shadow-2xl backdrop-blur-md transition-transform hover:scale-110">
                  <Play size={40} className="ml-[6px]" fill="currentColor" />
                </div>
              ) : (
                <div className="opacity-0 group-hover:opacity-100 flex h-24 w-24 items-center justify-center rounded-full bg-black/60 text-white shadow-2xl backdrop-blur-md transition-transform hover:scale-110 hover:bg-nova-accent/90">
                  <Pause size={40} fill="currentColor" />
                </div>
              )}
            </div>
            {status !== 'rendering' && (
              <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/90 to-transparent p-6 pt-20 translate-y-2 opacity-0 group-hover:opacity-100 group-hover:translate-y-0 transition-all duration-300">
                <div className="flex items-center gap-6">
                  <button onClick={togglePlay} className="text-white hover:text-nova-accent transition-colors">
                    {status === 'playing' ? <Pause size={28} fill="currentColor" /> : <Play size={28} fill="currentColor" />}
                  </button>
                  <div className="h-2 flex-1 overflow-hidden rounded-full bg-white/30 cursor-pointer hover:h-2.5 transition-all" onClick={(e) => {
                      const bounds = e.currentTarget.getBoundingClientRect();
                      const pct = (e.clientX - bounds.left) / bounds.width;
                      setProgress(pct * 100);
                    }}>
                    <div className="h-full bg-nova-accent shadow-[0_0_12px_rgba(99,102,241,1)] relative" style={{ width: `${progress}%`, transition: status === 'playing' ? 'width 0.1s linear' : 'none' }}>
                      <div className="absolute right-0 top-1/2 -translate-y-1/2 w-4 h-4 bg-white rounded-full shadow-md"></div>
                    </div>
                  </div>
                  <div className="text-sm font-semibold text-white font-mono min-w-[40px] text-right drop-shadow-md">
                    0:{Math.floor((progress / 100) * 30).toString().padStart(2, '0')}
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </>
  );
}
